### ISSUE TITLE
undefined symbol: opj_encoder_set_extra_option

### ISSUE THREAD

**Issue by amibuffalo** [andivis/screenshot-compare#1]
When I attempt to run python main.py  (does not change if I use —initial, etc) I receive the following Traceback.  Can anyone help me understand what has gone wrong?

Traceback (most recent call last):
  File "/usr/local/bin/screenshot-compare/main.py", line 20, in <module>
    from program.library.images import Images
  File "/usr/local/bin/screenshot-compare/program/library/images.py", line 2, in <module>
    import imgcompare
  File "/usr/local/lib/python3.9/site-packages/imgcompare/__init__.py", line 1, in <module>
    from .imgcompare import is_equal, image_diff_percent, image_diff, ImageCompareException
  File "/usr/local/lib/python3.9/site-packages/imgcompare/imgcompare.py", line 23, in <module>
    from PIL import Image
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: /usr/local/lib/python3.9/site-packages/PIL/_imaging.cpython-39-arm-linux-gnueabihf.so: undefined symbol: opj_encoder_set_extra_option

**Comment by amibuffalo** [comment]
The version of pillow needed to be downgraded
