### ISSUE TITLE
Something went wrong: [Errno 8] Exec format error: 'geckodriver'

### ISSUE THREAD

**Issue by amibuffalo** [andivis/screenshot-compare#2]
Anyone know what could be at issue here?  I installed the version in the readme and it is properly in the $PATH

***

Starting
[18:26:06][INFO]
Url 1 of 1: http://www.cnn.com
[18:26:06][ERROR]
Something went wrong: [Errno 8] Exec format error: 'geckodriver'
[18:26:06][ERROR]
handleException
[18:26:06][ERROR]
Traceback (most recent call last):
  File "/usr/local/bin/screenshot-compare/main.py", line 41, in run
    self.browser.getScreenshot(inputRow, self.currentFileName, self.options['secondsBeforeScreenshot'], self.options['browser'])
  File "/usr/local/bin/screenshot-compare/program/library/selenium.py", line 16, in getScreenshot
    self.initialize(browser)
  File "/usr/local/bin/screenshot-compare/program/library/selenium.py", line 49, in initialize
    self.driver = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 172, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'geckodriver'

[18:26:06][INFO]
Done

**Comment by amibuffalo** [comment]
Must be arm version on rasp pi
